language: c
sudo: required

env:
    global:
        HDF5_DIR=$HOME/hdf5
        MPI_RUN_COMMAND=''

notifications:
  email:
    recipients:
      - manodeep@gmail.com
      - jseiler@swin.edu.au
    on_success: change
    on_failure: always

matrix:
  fast_finish: true

  include:
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: mpicc
      env: COMPILER=mpicc PYTHON_VERSION=3.7 MPI_RUN_COMMAND='mpirun -np 5'
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -y libmpich-dev
        - which mpicc
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -q --yes -n test python=$PYTHON_VERSION nomkl
  - source activate test
  - conda install -q --yes -c anaconda gsl
  - if [[ “$COMPILER” != “mpicc” ]]; then conda install -q --yes -c conda-forge hdf5 ; fi
  - if [[ “$COMPILER” == “mpicc” ]]; then sh ./tests/install_hdf5.sh; fi
  - echo "About to Echo $PATH before exporting."
  - echo $PATH
  - export PATH="$HDF5_DIR/bin:$PATH"
  - echo "About to Echo $PATH after exporting."
  - echo $PATH
  - pip install -r requirements.txt 

script:
  - make -r CC=$COMPILER tests
